#!/bin/bash
#

# module load all intel/16.1 gcc/4.9.3 netcdf/4.4.0 netcdf-fortran/4.4.2 openmpi/1.10.2 lapack/3.6.0

FC=mpif90
CC=mpicc

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'
OMPFLAG='-fopenmp'
# CFLAGS='-fPIC'
# CFLAGS='-O3 -mieee-fp -xCORE-AVX2'
# LDADD=''

LIBS='-lmpi -lnetcdf -lnetcdff'
INCLUDES='-I$NETCDF_FORTRAN_INC'
INCLUDEDIRS=''
MPIINCLUDEDIR=''
MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'
MPI_HEADER_FILES_INC='./mpi_headers/mpif.h ./mpi_headers/mpiof.h ./mpi_headers/mpif_parameters.h'

NOOPTFLAGS='-O0 -fPIC'
NOOPTFILES='calc_oce_mxlayer.F fizhi_lsm.F fiszhi_clocstuff.F'

FFLAGS="$FFLAGS -W0 -WB -convert big_endian -assume byterecl -mcmodel=medium -shared-intel"
# FOPTIM='-O0 -noalign'
FOPTIM='-O3 -align -xCORE-AVX2'
# FOPTIM='-O3 -mieee-fp -xCORE-AVX2'
